# Site settings
title: Internet med versalt I
email: anders.sjunnesson@gmail.com
baseurl: ""
url: "http://andsju.github.io" 
github_username:  andsju
paginate: 3

# Build settings
markdown: kramdown

gems:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji