# Site settings
title: Thoughts about this and that
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just from my point of view!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andsju.github.io" # the base hostname & protocol for your site
twitter_username: andsju
github_username:  andsju

# Build settings
markdown: kramdown
