# Site settings
title: Internet med versalt I
email: anders.sjunnesson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tankar om webben...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andsju.github.io" # the base hostname & protocol for your site
twitter_username: andsju
github_username:  andsju
paginate: 3

# Build settings
markdown: kramdown
